self_filter:
  ros__parameters:

    # =========================
    # Frames
    # =========================
    # sensor_frame: "camera_link"

    # For spheres (single scale & padding)
    default_sphere_scale: 1.0
    default_sphere_padding: 0.01

    # For boxes (x,y,z scale & padding)
    default_box_scale: [1.0, 1.0, 1.0]
    default_box_padding: [0.01, 0.01, 0.01]

    # For cylinders (radial scale, vertical scale, radial padding, vertical padding)
    default_cylinder_scale: [1.0, 1.0]
    default_cylinder_padding: [0.01, 0.01]

    # =========================
    # Point cloud behavior
    # =========================
    keep_organized: false
    zero_for_removed_points: false
    invert: false
    # =========================
    # Robot links (Franka fr3)
    # =========================
    self_see_links:
      names:
        - fr3_link0
        - fr3_link1
        - fr3_link2
        - fr3_link3
        - fr3_link4
        - fr3_link5
        # - fr3_link6
        - fr3_link7
        - fr3_hand

      # =========================
      # Custom tuning per link
      # =========================

      fr3_link0:
        cylinder_scale: [1.75, 2.15]
        cylinder_padding: [0.01, 0.01]

      fr3_link1:
        cylinder_scale: [1.0, 2.2]
        cylinder_padding: [0.01, 0.01]

      fr3_link2:
        cylinder_scale: [0.6, 2.5]
        cylinder_padding: [0.03, 0.01]

      fr3_link3:
        cylinder_scale: [1.0, 2.8]
        cylinder_padding: [0.02, 0.02]

      fr3_link4:
        cylinder_scale: [0.6, 2.2]
        cylinder_padding: [0.035, 0.03]

      fr3_link5:
        cylinder_scale: [1.4, 4.4]
        cylinder_padding: [0.01, 0.01]

      # fr3_link6:
      #   cylinder_scale: [1.0, 1.0]
      #   cylinder_padding: [0.02, 0.02]

      fr3_link7:
        cylinder_scale: [0.5, 1.6]
        cylinder_padding: [0.02, 0.02]

      fr3_hand:
        box_scale: [0.6, 2.0, 1.8]
        box_padding: [0.03, 0.03, 0.02]