planning_plugin: task_planner/TaskPlannerManager
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints

start_state_max_bounds_error: 0.1

config:
  max_iterations: 500
  step_size: 0.05
  goal_bias: 0.1
  goal_tolerance: 0.02
  clearance: 0.02